language: scala
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0-RC1
jdk:
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
    - scala: 2.12.0-RC1
      jdk: oraclejdk7
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
